### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by msva** [gvvaughan/specl#26]
`specl` compilation requires `lyaml` library (makefile **requires** to build docs, and calls `help2man`). `help2man`, in turn, trying to call `./specl --help` and fails because of `yaml` module not found.
`lyaml`, in turn, **requires** (according to bootstrap.conf there) `specl` for building and installing.

Here we get circular dependencies...

// offtop: and again offline installation troubles there in `lyaml` and in `luaposix`

**Comment by gvvaughan** [comment]
lyaml compiles, installs and runs just fine without specl, you only need specl to run the self tests.

or you can `luarocks install specl` to bootstrap your own builds if you'd prefer to see your self-built lyaml pass it's own tests before installing it.
