### ISSUE TITLE
specl r.18bed40 lib/specl/std.lua requires std.debug_init but where is the source?

### ISSUE THREAD

**Issue by Corin-EU** [gvvaughan/specl#29]
Lua v5.3.5

In the latest revision of specl r.18bed40, specl uses the supplied file lib/specl/std.lua which
requires std.debug_init.

I have the latest lua stdlib revision r.a632078 installed and this provides debug but not debug_init. 

On 16 October 16, 2017 gvvaughan made a commit to lua-stdlib titled
"debug_init: split into its own package."  

Under lua-stdlib on Github there is a repository for _debug but that does not contain debug_init, nor can I find a respository under gvvaughan for debug_init.  A Github search for debug_init does not find anything marked as language "lua", nor is the location for the source revealed by a web search using the terms gvvaughan + debug_init.

Please advise where the source repository for debug_init can be found and add it to the requirements in the Readme file.

**Comment by gvvaughan** [comment]
Hi Corin,

master is in flux, and likely doesn't work properly yet in any case - you'll definitely have more success with the release branch, or better yet with a tagged release of Specl.

If you really want to work on development of the unfinished rewrite on master, the module dependencies are all listed in the rockspec file - again, referring to released luarocks which are known to work, not the master development branch of the respective repoitories.

HTH,
Gary
